### ISSUE TITLE
creating new subdomains needs improvement

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-farmer#11]
When creating a new subdomain wiki you're asked for two values: name and subdomain. It is not initially clear what both are. The name filed should probably be renamed to "Wiki Title" as that seem what it is used for.

The subdomain currently expects a full qualified domain name, not a subdomain only. This should be improved by either
* when a non-dotted name is given append the current wiki domain (problematic)
* do not accept a non-dotted name and ask for a proper FQDN

The check for the domain setup (AJAX) is only done *after* the subdomain wiki has been created. This should be done beforehand. When the check fails, the setup should not continue.

The error message when the AJAX request fails is somewhat cryptical. How about something like this: "The specified domain name could not be verified to be part of this farm setup. This is most probably a DNS or web server misconfiguration. Please refer to the farm plugin documentation on how to setup (sub-)domain farms."

**Comment by micgro42** [comment]
The extra check for the domain setup (get request) has been introduced in commit ba663b1, however I cannot test it. It also doesn't take into account that some TLD defacto include a dot, like `sub.domain.co.uk`. It currently requires 2 dots to be present.

The requested localisation updates have been implemented by commits 29b841f and ba663b1.
