### ISSUE TITLE
Error 500: Check for missing PHP gd extension before/during animal creation

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-farmer#22]
If the gd extension of php is not installed or not activated in php.ini, then an 500 error is thrown upon creation of a new animal. The error-message points to: https://github.com/splitbrain/php-ringicon/blob/8ef1c63b952e6cef1df3ffc141089609ae99570f/src/RingIcon.php#L174

**Comment by splitbrain** [comment]
fixed in b263debe7429d71cd37a77d3a34e8d8321252bc3
