### ISSUE TITLE
Animal Admin can upgrade and remove plugins

### ISSUE THREAD

**Issue by Digitalin** [cosmocode/dokuwiki-plugin-farmer#26]
Hi, 
First of all, thanks for this plugin that goes well. 

I wonder if it is normal to have a FQDN for the animal folder name in farm directory: 

> animal.test.local
 
where "test.local" is the farmer ? or it is a  virtualhost settings problem. It works well, it is just a question as I watched the [video made by Anika](https://www.youtube.com/watch?v=vgB9aJ-fRzY) on this topic. 

When you create an animal with option : Create new admin user "admin", the admin has all the rights, included to remove or upgrade plugins. 
It is nice animal admin can activate or deactivate plugins for his own need  but not to upgrade or remove plugins that can affect farmer and all animals.  
The other way I see to restrain rights, following the current admin to animal is to create a manager role but it is poor in comparison. I haven't yet tested everything to see what admin animal can affect to the whole wiki but it would be appreciable to have an admin role for animal, without this right to upgrade and remove plugins.

**Comment by micgro42** [comment]
There is already a major refactoring underway, which should address this issue and greatly enhance the plugin. If you are interested, take a look at the ``refactor`` branch. This should be merged either this or next month.

**Comment by splitbrain** [comment]
fixed since merge

**Comment by Digitalin** [comment]
Well done :+1: 

And you had a good idea to give also a Base domain if needed. I am not sure yet of the use case. 
I imagine a web site, let say : beautiful-wiki.org that would like to provide wikis but to make a difference with this own site,  would find nice to give a Base Domain : beautiful-farms.org for sub namespace : metoo.beautiful-farms.org for instance.
It is easy to give a  FQDN to an animal, even with dash. mon-joli-wiki.org and in this case, the animal folder takes this name and not when it is a sub-domain. 
Excellent.
