### ISSUE TITLE
Setup farmer with secured data and conf

### ISSUE THREAD

**Issue by ivangretsky** [cosmocode/dokuwiki-plugin-farmer#52]
Good day!
Thanks for this plugin. Was going to try it for months, and today is THE day,

I got an dokuwiki existing installation. I moved data and conf folders out of web root as it was advised [here](https://www.dokuwiki.org/security#move_directories_out_of_docroot). I have creted `inc/preload.php` and modified `DOKU_CONF` constant there. 

When installing dokuwiki-plugin-farmer this file gets ovewritten. Now I do not know where should I define `DOKU_CONF` to make existing installation (the farmer) be still accessible, and not have any trouble (like notices and I do not know what else to come) in the future with animals.

Could you please suggest how to configure Dokuwiki in this case?

**Comment by ivangretsky** [comment]
I guess I can modify [this line](https://github.com/cosmocode/dokuwiki-plugin-farmer/blob/6c5b4ee935a5d52d29ec6f0ef4fc618023373881/DokuWikiFarmCore.php#L73), but is it upgrade-safe way?

**Comment by ivangretsky** [comment]
I think there are other issues when working with "secured" setup (conf and data folders moved out of the web root). When I create new animals, the inheritance work with the default folder not taking into account the moved folders. Or am I missing something?

**Comment by splitbrain** [comment]
Yeah moving the conf directory of the farmer to a non-standard path is not really supported by this plugin. And I don't see an easy way to do that.
