### ISSUE TITLE
Easy way to export/import animals ?

### ISSUE THREAD

**Issue by 3615pipou** [cosmocode/dokuwiki-plugin-farmer#53]
Could it be possible to add the possibility to easily export/import an animal ?  It could export/import all content, history of content, media, configuration and all the users informations etc. of my personal wiki.

The main purpose is when I want to quite a farmer for an other one.

Maybe an option could be : 
- export/import as an animal
- export/import a fully functional and independent wiki

**Comment by 3615pipou** [comment]
This function should be accessible for the admin of the animal, maybe in the administration page : export a zip of the wiki. 

This way the admin of the animal wouldn't need to ask anything to the farmer to quite the farm.

**Comment by splitbrain** [comment]
This is a bit beyond the scope of this plugin. This would be more like a backup plugin and not necessarily targeted at farm setups.

**Comment by 3615pipou** [comment]
yes, there is already a backup plugin but it doesn't seem to be updated https://www.dokuwiki.org/plugin:backup
