### ISSUE TITLE
Empty login page on an animal site (“Greebo” on PHP 5.6.21.)

### ISSUE THREAD

**Issue by shimmtak** [cosmocode/dokuwiki-plugin-farmer#58]
Hi, thank you for your nice tools.
I found the animal site's login page has been empty on the newest dokuwiki.
* I created an animal site, and tried to login to it, click the "login" link, then the screen became empty (blank).
* On the farm site, I can login it as usual. 
* With debug mode, dbglog($msg) to the inc/Action/Login.php did not show any log.
* The environment : “Greebo” on  PHP 5.6.21. CentOS7 (4.14.33-300.1.1)
(With “Frusterick Manners” on PHP 5.3.3, CentOS6(2.6.32-642.6.2), I can login the animal/farm sites as usual.)
* I tried with dokuwiki and vector templates.

**Comment by shimmtak** [comment]
Yes, some brower(chrome) suggested it was 500 error, but I had no error message in the HTTPD log. (The environment is on a  hosting service, so I could not grab the error message. Sorry.)
By the way, I found that the issue was related to the Farming->Configuration->Plugin State setting.
When I disabled the setting, the issue was reproduced, but not when enabled. (I slightly relieved that I might be able to operate my site !) 
I rechecked on the “Frusterick Manners” on PHP 5.3.3, the issue was not reproduced. It was reproduced only on Greebo.

**Comment by micgro42** [comment]
Could you try installing the [showphperrors plugin](https://www.dokuwiki.org/plugin:showphperrors) and activate the `showphperrors` option? This might print out the fatal error. (Don't use this plugin except for debugging. It might break other things or leak sensitive data)

**Comment by shimmtak** [comment]
Oh, thank you. After installed the showphpeperrors plugin, I found that the problem was caused by the [fedauth plugin](https://www.dokuwiki.org/plugin:fedauth). I had disabled it before, but it was needed to uninstall it. Thank you for your help and nice tools.
