### ISSUE TITLE
Hogfather: cannot change animal's config field to default value

### ISSUE THREAD

**Issue by nik-mb** [cosmocode/dokuwiki-plugin-farmer#71]
I have a problem with the setting of the config field 'hideLoginLink' (plugin 'bootstrap3'). This setting can hide the login button.
Maybe it's only an example, and other plugin config fields are concerned too.

The default value of this filed is "off":
$conf['tpl']['bootstrap3']['hideLoginLink'] = 0;

If in the farmer the value is non-default 
hideLoginLink = 1
this value of the config field is inherited to the animals.

The problem: 
the animal runs with hidden login button, but the value will not be written to the animal's local.php, and at dokuwiki's config page the config field is unchecked.
So, it's not possible to set in an specific animal the value of 'hideLoginLink' back to the default value
hideLoginLink = 0

Even if I add the line
$conf['tpl']['bootstrap3']['hideLoginLink'] = 0;
manually to the animal's local.php, this line will be deleted after the next changing of the configuration via dokuwiki.

This problem occurs only with "Hogfather", at "Greebo" the config line with the inherited value is written to the animal's config file.

**Comment by Klap-in** [comment]
Maybe this is related? https://github.com/splitbrain/dokuwiki/pull/3349 however, I'm not sure.

**Comment by NikolausMB** [comment]
> Maybe this is related? [splitbrain/dokuwiki#3349](https://github.com/splitbrain/dokuwiki/pull/3349) however, I'm not sure.

Thank you. I think it's a Farm specific problem. Maybe not all configuration settings are concerned.
I guess:
1. after editing the dokuwiki configuration page, hogfather deletes entries in the local.php which are set to default values,
2. animals inherit the farmer's configuration settings if they don't have their own setting.
Therefore, an animal's configuration field cannot have default values if this field has a non-default value in the farmer. 
Workaround: set all configuration fields of the farmer to default values.
... but that's just the interpretation of my trial and error attempts, I'm not a software engeneer.

**Comment by annda** [comment]
Works with DokuWiki Jack Jackrum and the current versions of farmer and bootstrap3.
