### ISSUE TITLE
Restricting access to farmer install wiki instance?

### ISSUE THREAD

**Issue by boardtc** [cosmocode/dokuwiki-plugin-farmer#73]
I have installed a farm using the plugin for one animal and it works as expected with my ported farm - I overwrote all the conf and data directories. 

A simple redirect in cPanel means the bang in the URL is a non-issue.

However, the farmer install, original URL for the DokuWiki installation is still accessible and pages can be created there. I can't see a way in the plugin how I can restrict access to that page. Did I miss something?

**Comment by splitbrain** [comment]
Restrict access in the farmer as in any other wiki using the ACLs.
