### ISSUE TITLE
"Igor" broke farm animals

### ISSUE THREAD

**Issue by phil-ide** [cosmocode/dokuwiki-plugin-farmer#75]
I upgraded my wiki farm to "Igor" rc2022-06-26, and all my animals broke. The farmer ran fine.

I determined that the log folder created had the wrong owner and group (both root), changed them to www-data:

sudo chown www-data:www-data /var/www/data/log

- and and my animal were accessible again. This may be a problem with the "upgrade" plugin rather than the farmer plugin, but I'm reporting it here for reference. This is probably not going to be an issue on Windows OS.

**Comment by splitbrain** [comment]
The farmer plugin only creates directories when creating a new animal. So if the log dir was created, it was done (maybe?) by DokuWiki. But I don't see how a properly set up DokuWiki should be able to create directories owned by root. Maybe you're running some docker setup? In any case I don't see what the farmer plugin (or dokuwiki) could do about it.
