### ISSUE TITLE
Change child wikis from animals to gardens

### ISSUE THREAD

**Issue by iatttmp** [cosmocode/dokuwiki-plugin-farmer#85]
### Feature Description

Here's the thing. Animals are not the only things that farmers grow. Gardens are cordonned off, unmoving, and intended to support growth over time. Animals don't do any of that. I suggest that the Garden metaphor, instead of "Animals" is much gentler and appropriate.

I should add that the Farm plugin is great. I'm playing with it and it works well. I'm thinking it'd be very, very useful in teaching situations, giving each team or individual learner their place to pile their research and compositions.

**Comment by splitbrain** [comment]
If you send a PR to change the wording and volunteer to update the documentation, I will consider this. Alternatively you're free to hire CosmoCode to implement this.
